name: Onboard Microservice to Helm

on:
  push:
  workflow_dispatch:

jobs:
    build-docker-image:
      runs-on: self-hosted

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Build and Push the image
          uses: julanu/composite-actions/docker-build-push@test-release
          with:
            registry_user: ${{ secrets.DOCKERID }}
            registry_pwd: ${{ secrets.DOCKERKEY }}
            image_name: mjula/images
            tag: simplepython
            dockerfile: ./Dockerfile
            platforms: linux/amd64